# Generated by Django 5.2.3 on 2025-06-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_age', models.PositiveSmallIntegerField()),
                ('estimated_retirement_age', models.PositiveSmallIntegerField()),
                ('current_yearly_salary', models.PositiveBigIntegerField()),
                ('estimated_salary_raise', models.FloatField()),
                ('estimated_bonus', models.FloatField()),
                ('current_yearly_other_income', models.PositiveSmallIntegerField()),
                ('estimated_other_income_increase', models.FloatField()),
                ('current_yearly_fixed_costs', models.PositiveBigIntegerField()),
                ('estimated_fixed_costs_inflation', models.FloatField()),
                ('current_yearly_cost_of_living', models.PositiveBigIntegerField()),
                ('estimated_cost_of_living_inflation', models.FloatField()),
                ('current_yearly_health_insurance_cost', models.PositiveBigIntegerField()),
                ('estimated_health_insurance_inflation', models.FloatField()),
                ('estimated_tax_rate', models.FloatField()),
                ('current_hsa_balance', models.PositiveBigIntegerField()),
                ('current_hsa_yearly_contribution_limit', models.PositiveBigIntegerField()),
                ('esitmated_hsa_yearly_return', models.FloatField()),
                ('current_401k_balance', models.PositiveBigIntegerField()),
                ('current_401k_yearly_contribution_limit', models.PositiveBigIntegerField()),
                ('current_401k_employer_contribution', models.PositiveBigIntegerField()),
                ('esitmated_401k_yearly_return', models.FloatField()),
                ('current_ira_balance', models.PositiveBigIntegerField()),
                ('current_ira_yearly_contribution_limit', models.PositiveBigIntegerField()),
                ('esitmated_ira_yearly_return', models.FloatField()),
                ('current_iba_balance', models.PositiveBigIntegerField()),
                ('esitmated_iba_yearly_return', models.FloatField()),
            ],
        ),
    ]
