# Generated by Django 5.2.3 on 2025-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='current_401k_employer_contribution',
            field=models.FloatField(),
        ),
    ]
