# Generated by Django 4.2.23 on 2025-07-11 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FIRE', '0002_alter_simulation_current_401k_employer_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
