# Generated by Django 4.2.23 on 2025-07-11 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0003_simulation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
