# Generated by Django 4.2.23 on 2025-07-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0004_alter_simulation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='name',
            field=models.CharField(default='Test Simulation', max_length=50),
            preserve_default=False,
        ),
    ]
