# Generated by Django 4.2.23 on 2025-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0005_simulation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='estimated_401k_yearly_contribution_limit_step',
            field=models.PositiveBigIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_hsa_yearly_contribution_limit_step',
            field=models.PositiveBigIntegerField(default=150),
            preserve_default=False,
        ),
    ]
