# Generated by Django 4.2.23 on 2025-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0006_simulation_estimated_401k_yearly_contribution_limit_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='estimated_ira_yearly_contribution_limit_step',
            field=models.PositiveBigIntegerField(default=300),
            preserve_default=False,
        ),
    ]
