# Generated by Django 4.2.23 on 2025-07-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0007_simulation_estimated_ira_yearly_contribution_limit_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='hsa_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
