# Generated by Django 4.2.23 on 2025-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0008_simulation_hsa_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='final_net_worth',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
