# Generated by Django 4.2.23 on 2025-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0009_simulation_created_at_simulation_final_net_worth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='hsa_enrollment',
            field=models.BooleanField(default=True),
        ),
    ]
