# Generated by Django 4.2.23 on 2025-08-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0010_alter_simulation_hsa_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='hsa_enrollment',
        ),
        migrations.AddField(
            model_name='simulation',
            name='hsa_enrollment_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
