# Generated by Django 4.2.23 on 2025-08-09 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0011_remove_simulation_hsa_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='estimated_lumpsum_payment_ages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_lumpsum_payment_amounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), null=True, size=None),
        ),
    ]
