# Generated by Django 4.2.23 on 2025-08-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0012_simulation_estimated_lumpsum_payment_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='estimated_lumpsum_payment_ages',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='estimated_lumpsum_payment_amounts',
            field=models.JSONField(null=True),
        ),
    ]
