# Generated by Django 4.2.23 on 2025-08-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0013_alter_simulation_estimated_lumpsum_payment_ages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='estimated_coastfire_age',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
    ]
