# Generated by Django 4.2.23 on 2025-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0014_simulation_estimated_coastfire_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='current_asset_values',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_asset_value_growths',
            field=models.JSONField(null=True),
        ),
    ]
