# Generated by Django 4.2.23 on 2025-08-16 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0015_simulation_current_asset_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='estimated_fixed_cost_adjustment_ages',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_fixed_cost_adjustments',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_variable_cost_adjustment_ages',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_variable_cost_adjustments',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='current_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='estimated_coastfire_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='estimated_retirement_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(101), django.core.validators.MinValueValidator(2)]),
        ),
    ]
