# Generated by Django 4.2.23 on 2025-08-18 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0016_simulation_estimated_fixed_cost_adjustment_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='estimated_coastfire_age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
