# Generated by Django 4.2.23 on 2025-08-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0017_alter_simulation_estimated_coastfire_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='current_yearly_cost_of_living',
            new_name='current_yearly_variable_costs',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='estimated_lumpsum_payment_ages',
            new_name='estimated_lumpsum_income_ages',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='estimated_lumpsum_payment_amounts',
            new_name='estimated_lumpsum_income_amounts',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='estimated_cost_of_living_inflation',
            new_name='estimated_variable_costs_inflation',
        ),
        migrations.AddField(
            model_name='simulation',
            name='asset_names',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_lumpsum_expense_ages',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='estimated_lumpsum_expense_amounts',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='fixed_cost_adjustment_names',
            field=models.JSONField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='lumpsum_expense_names',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='lumpsum_income_names',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='variable_cost_adjustment_names',
            field=models.JSONField(max_length=50, null=True),
        ),
    ]
