# Generated by Django 4.2.23 on 2025-08-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0018_rename_current_yearly_cost_of_living_simulation_current_yearly_variable_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='estimated_tax_rate_step',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
