# Generated by Django 4.2.23 on 2025-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0020_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
