# Generated by Django 4.2.23 on 2025-09-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRE', '0022_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='final_net_worth',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
