from django.db import models

# Create your models here.
class Simulation(models.Model):
    current_age = models.PositiveSmallIntegerField()
    estimated_retirement_age = models.PositiveSmallIntegerField()
    current_yearly_salary = models.PositiveBigIntegerField()
    estimated_salary_raise = models.FloatField()
    estimated_bonus = models.FloatField()
    current_yearly_other_income = models.PositiveSmallIntegerField()
    estimated_other_income_increase = models.FloatField()
    current_yearly_fixed_costs = models.PositiveBigIntegerField()
    estimated_fixed_costs_inflation = models.FloatField()
    current_yearly_cost_of_living = models.PositiveBigIntegerField()
    estimated_cost_of_living_inflation = models.FloatField()
    current_yearly_health_insurance_cost = models.PositiveBigIntegerField()
    estimated_health_insurance_inflation = models.FloatField()
    estimated_tax_rate = models.FloatField()
    current_hsa_balance = models.PositiveBigIntegerField()
    current_hsa_yearly_contribution_limit = models.PositiveBigIntegerField()
    esitmated_hsa_yearly_return = models.FloatField()
    current_401k_balance = models.PositiveBigIntegerField()
    current_401k_yearly_contribution_limit = models.PositiveBigIntegerField()
    current_401k_employer_contribution = models.FloatField()
    esitmated_401k_yearly_return = models.FloatField()
    current_ira_balance = models.PositiveBigIntegerField()
    current_ira_yearly_contribution_limit = models.PositiveBigIntegerField()
    esitmated_ira_yearly_return = models.FloatField()
    current_iba_balance = models.PositiveBigIntegerField()
    esitmated_iba_yearly_return = models.FloatField()